name: "[Test] scheduled cron"
on:
  schedule:
    - cron: 05 10 * * *

jobs:
  create_issue:
    name: Création d'un ticket test
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create reccurent issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Test issue
          ASSIGNEES: lgatibel 
          BODY: |
            # Tâche récurrente.

            Test body
          PINNED: true
          CLOSE_PREVIOUS: false
